server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: dish-api
        uri: lb://dish-api
        predicates:
        - Path=/dish/**
        filters:
        - RewritePath=/dish/(?<path>.*), /$\{path} 
      - id: food-store-api
        uri: lb://food-store-api
        predicates:
        - Path=/food/**
        filters:
        - RewritePath=/food/(?<path>.*), /$\{path} 
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: dish
        url: /v3/api-docs/dish
      - name: food
        url: /v3/api-docs/food